version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev 
    ports:
      - 5173:5173
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
  test:
    build: 
      context: .
      dockerfile: Dockerfile.dev 
    ports:
      - 5174:5174
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    command: ["npm","run","test:unit"]
    